### ISSUE TITLE
The npm package (v1.0.0) used `./build/Debug` as native module path

### ISSUE THREAD

**Issue by jhen0409** [ccnokes/electron-named-image#1]
@ccnokes maybe you forgot to change back it when you publish it? :)

```js
// change from Release to Debug when debugging
const addon = require('./build/Debug/NamedImage');
```

**Comment by ccnokes** [comment]
😱 I'll fix it shortly. Thanks for reporting and that's cool you're using this in your project!

**Comment by ccnokes** [comment]
Should be fixed now on npm. 👍
