### ISSUE TITLE
App will crash when I set a wrong name

### ISSUE THREAD

**Issue by jhen0409** [ccnokes/electron-named-image#2]
[Travis CI builds](https://travis-ci.org/jhen0409/react-native-debugger/builds/249020284) (xcode7.3 and default -> 10.11, xcode 6.4 -> 10.10)

I think this is because the old versions doesn't supported NSTouchBar icons, and I tried the app will crashed when I use a wrong name.

Should we just return a empty buffer or null if the icon is invalid? Or throw a JS error?

**Comment by ccnokes** [comment]
Yeah I'm throwing an error in Objective-C land here https://github.com/ccnokes/electron-named-image/blob/master/named-image.mm#L17 if it's an invalid image. 

I agree that just returning an empty buffer is a bit more friendly and covers that use case described. I hadn't thought of that. I'll get something working soon, so hopefully a fixed release tonight or tomorrow (US time).

**Comment by ccnokes** [comment]
Ok just published 1.0.2. Try that and see if it works 😸.

**Comment by jhen0409** [comment]
It works fine now, thanks for quick response and great work! :)
